# Generated by Django 3.2.14 on 2022-08-12 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True, verbose_name='User ID')),
                ('email', models.EmailField(max_length=354, unique=True, verbose_name='email')),
                ('lastname', models.CharField(blank=True, help_text='Last name', max_length=200, null=True)),
                ('firstname', models.CharField(blank=True, help_text='First name', max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('account_type', models.PositiveIntegerField(choices=[(0, 'STUDENT'), (1, 'STAFF')], null=True)),
                ('email_verification_pin', models.PositiveIntegerField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_female_porter', models.BooleanField(default=False)),
                ('is_male_porter', models.BooleanField(default=False)),
                ('is_dsa', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default='v-764532257963696', null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
            ],
            options={
                'verbose_name_plural': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, help_text='Parent Email Address', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Parent Phone Number', max_length=20, null=True)),
                ('relationship', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], help_text='Gender', max_length=500, null=True)),
                ('department', models.CharField(blank=True, choices=[('Physics', 'Physics'), ('English', 'English'), ('Economics', 'Economics'), ('Chemical Sciences', 'Chemical Sciences'), ('Biological Sciences', 'Biological Sciences'), ('Mathematical Sciences', 'Mathematical Sciences'), ('Accounting and Finance', 'Accounting and Finance'), ('Business Administration', 'Business Administration'), ('Mass Communication and Media Studies', ' Mass Communication and Media Studies'), ('Philosophy and Religious Studies', 'Philosophy and Religious Studies'), ('Political Science and International Relations', 'Political Science and International Relations')], help_text='Department', max_length=500, null=True)),
                ('hall_of_residence', models.CharField(blank=True, choices=[('Assumption Hall', 'Assumption Hall'), ('Divine Mercy Hall', 'Divine Mercy Hall')], max_length=500, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=500, null=True)),
                ('parent_email', models.EmailField(default='user@ems.com', max_length=254)),
                ('parent_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Profile',
            },
        ),
    ]
