# Generated by Django 3.2.14 on 2022-08-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_account_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('reason', models.TextField(help_text='Reasons for applying for exeat')),
                ('leave_on', models.DateField(blank=True, null=True)),
                ('return_on', models.DateField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('residence', models.CharField(blank=True, max_length=500, null=True)),
                ('is_approved_DSA', models.BooleanField(default=False)),
                ('is_approved_by_hall_admin', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
            options={
                'verbose_name_plural': 'Exeat Form',
            },
        ),
    ]
